server:
  port: 6322

logging:
  file:
    path: /Users/yuanjinxiu/cake-ops/logs

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181

easy:
  sso:
    client:
      enable: true
      client-type: web
      sso-server: http://127.0.0.1:8765/
      login-url: http://127.0.0.1:8765/sso/loginPage
      sso-callback-url: http://127.0.0.1:8765/sso/code
      logout-url: /sso/logout
      ignore-urls: /ok,/sso/loginPage,/sso/login,/oauth/login
      ignore-resources: .js, .css, .jpg, .png, .ico, .html
      ajax-failure-response:
        content-type: application/json
        code: 401
        msg: 用户未登录

    redis:
      address: redis://127.0.0.1:6379