package com.rany.ops.infra.po;

import java.util.Date;

public class RolePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.app_code
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.tenant_id
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_key
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String roleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_desc
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.creator
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.modifier
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.gmt_create
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.gmt_modified
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.is_deleted
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.parent_role_id
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private Long parentRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.app_code
     *
     * @return the value of role.app_code
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.app_code
     *
     * @param appCode the value for role.app_code
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.tenant_id
     *
     * @return the value of role.tenant_id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.tenant_id
     *
     * @param tenantId the value for role.tenant_id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_key
     *
     * @return the value of role.role_key
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_key
     *
     * @param roleKey the value for role.role_key
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_desc
     *
     * @return the value of role.role_desc
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_desc
     *
     * @param roleDesc the value for role.role_desc
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.creator
     *
     * @return the value of role.creator
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.creator
     *
     * @param creator the value for role.creator
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.modifier
     *
     * @return the value of role.modifier
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.modifier
     *
     * @param modifier the value for role.modifier
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.gmt_create
     *
     * @return the value of role.gmt_create
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.gmt_create
     *
     * @param gmtCreate the value for role.gmt_create
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.gmt_modified
     *
     * @return the value of role.gmt_modified
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.gmt_modified
     *
     * @param gmtModified the value for role.gmt_modified
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.is_deleted
     *
     * @return the value of role.is_deleted
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.is_deleted
     *
     * @param isDeleted the value for role.is_deleted
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.parent_role_id
     *
     * @return the value of role.parent_role_id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public Long getParentRoleId() {
        return parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.parent_role_id
     *
     * @param parentRoleId the value for role.parent_role_id
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setParentRoleId(Long parentRoleId) {
        this.parentRoleId = parentRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}