package com.rany.ops.infra.po;

import java.util.Date;

public class RoleMenuPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.app_code
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.tenant_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.is_deleted
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.creator
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.modifier
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.gmt_create
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.gmt_modified
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.app_code
     *
     * @return the value of role_menu.app_code
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.app_code
     *
     * @param appCode the value for role_menu.app_code
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.tenant_id
     *
     * @return the value of role_menu.tenant_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.tenant_id
     *
     * @param tenantId the value for role_menu.tenant_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menuId the value for role_menu.menu_id
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.is_deleted
     *
     * @return the value of role_menu.is_deleted
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.is_deleted
     *
     * @param isDeleted the value for role_menu.is_deleted
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.creator
     *
     * @return the value of role_menu.creator
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.creator
     *
     * @param creator the value for role_menu.creator
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.modifier
     *
     * @return the value of role_menu.modifier
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.modifier
     *
     * @param modifier the value for role_menu.modifier
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.gmt_create
     *
     * @return the value of role_menu.gmt_create
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.gmt_create
     *
     * @param gmtCreate the value for role_menu.gmt_create
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.gmt_modified
     *
     * @return the value of role_menu.gmt_modified
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.gmt_modified
     *
     * @param gmtModified the value for role_menu.gmt_modified
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}