package com.rany.ops.infra.po;

import java.util.Date;

public class UserRolePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.app_code
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.tenant_id
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_id
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.creator
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.modifier
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.gmt_create
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.gmt_modified
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.is_deleted
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.status
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.app_code
     *
     * @return the value of user_role.app_code
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.app_code
     *
     * @param appCode the value for user_role.app_code
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.tenant_id
     *
     * @return the value of user_role.tenant_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.tenant_id
     *
     * @param tenantId the value for user_role.tenant_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_id
     *
     * @return the value of user_role.user_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_id
     *
     * @param userId the value for user_role.user_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param roleId the value for user_role.role_id
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.creator
     *
     * @return the value of user_role.creator
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.creator
     *
     * @param creator the value for user_role.creator
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.modifier
     *
     * @return the value of user_role.modifier
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.modifier
     *
     * @param modifier the value for user_role.modifier
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.gmt_create
     *
     * @return the value of user_role.gmt_create
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.gmt_create
     *
     * @param gmtCreate the value for user_role.gmt_create
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.gmt_modified
     *
     * @return the value of user_role.gmt_modified
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.gmt_modified
     *
     * @param gmtModified the value for user_role.gmt_modified
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.is_deleted
     *
     * @return the value of user_role.is_deleted
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.is_deleted
     *
     * @param isDeleted the value for user_role.is_deleted
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.status
     *
     * @return the value of user_role.status
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.status
     *
     * @param status the value for user_role.status
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}