package com.rany.acl.infra.po;

import java.util.Date;

public class PermissionPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.resource_name
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.resource_path
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String resourcePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_permission.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.id
     *
     * @return the value of rbac_permission.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.id
     *
     * @param id the value for rbac_permission.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.app_code
     *
     * @return the value of rbac_permission.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.app_code
     *
     * @param appCode the value for rbac_permission.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.tenant_id
     *
     * @return the value of rbac_permission.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.tenant_id
     *
     * @param tenantId the value for rbac_permission.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.resource_name
     *
     * @return the value of rbac_permission.resource_name
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.resource_name
     *
     * @param resourceName the value for rbac_permission.resource_name
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.resource_path
     *
     * @return the value of rbac_permission.resource_path
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.resource_path
     *
     * @param resourcePath the value for rbac_permission.resource_path
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath == null ? null : resourcePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.creator
     *
     * @return the value of rbac_permission.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.creator
     *
     * @param creator the value for rbac_permission.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.modifier
     *
     * @return the value of rbac_permission.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.modifier
     *
     * @param modifier the value for rbac_permission.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.gmt_create
     *
     * @return the value of rbac_permission.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.gmt_create
     *
     * @param gmtCreate the value for rbac_permission.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.gmt_modified
     *
     * @return the value of rbac_permission.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.gmt_modified
     *
     * @param gmtModified the value for rbac_permission.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_permission.is_deleted
     *
     * @return the value of rbac_permission.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_permission.is_deleted
     *
     * @param isDeleted the value for rbac_permission.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}