package com.rany.acl.infra.po;

import java.util.Date;

public class PermissionPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.app_code
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.tenant_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.resource_type
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.resource_name
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.resource_path
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String resourcePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.creator
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.modifier
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.gmt_create
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.gmt_modified
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.is_deleted
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.ref_menu_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private Long refMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.status
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.app_code
     *
     * @return the value of permission.app_code
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.app_code
     *
     * @param appCode the value for permission.app_code
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.tenant_id
     *
     * @return the value of permission.tenant_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.tenant_id
     *
     * @param tenantId the value for permission.tenant_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.resource_type
     *
     * @return the value of permission.resource_type
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.resource_type
     *
     * @param resourceType the value for permission.resource_type
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.resource_name
     *
     * @return the value of permission.resource_name
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.resource_name
     *
     * @param resourceName the value for permission.resource_name
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.resource_path
     *
     * @return the value of permission.resource_path
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.resource_path
     *
     * @param resourcePath the value for permission.resource_path
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath == null ? null : resourcePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.creator
     *
     * @return the value of permission.creator
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.creator
     *
     * @param creator the value for permission.creator
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.modifier
     *
     * @return the value of permission.modifier
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.modifier
     *
     * @param modifier the value for permission.modifier
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.gmt_create
     *
     * @return the value of permission.gmt_create
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.gmt_create
     *
     * @param gmtCreate the value for permission.gmt_create
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.gmt_modified
     *
     * @return the value of permission.gmt_modified
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.gmt_modified
     *
     * @param gmtModified the value for permission.gmt_modified
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.is_deleted
     *
     * @return the value of permission.is_deleted
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.is_deleted
     *
     * @param isDeleted the value for permission.is_deleted
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.ref_menu_id
     *
     * @return the value of permission.ref_menu_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public Long getRefMenuId() {
        return refMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.ref_menu_id
     *
     * @param refMenuId the value for permission.ref_menu_id
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setRefMenuId(Long refMenuId) {
        this.refMenuId = refMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.status
     *
     * @return the value of permission.status
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.status
     *
     * @param status the value for permission.status
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}