package com.rany.acl.infra.po;

import java.util.Date;

public class UserRolePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.user_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.role_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rbac_user_role.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.id
     *
     * @return the value of rbac_user_role.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.id
     *
     * @param id the value for rbac_user_role.id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.app_code
     *
     * @return the value of rbac_user_role.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.app_code
     *
     * @param appCode the value for rbac_user_role.app_code
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.user_id
     *
     * @return the value of rbac_user_role.user_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.user_id
     *
     * @param userId the value for rbac_user_role.user_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.tenant_id
     *
     * @return the value of rbac_user_role.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.tenant_id
     *
     * @param tenantId the value for rbac_user_role.tenant_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.role_id
     *
     * @return the value of rbac_user_role.role_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.role_id
     *
     * @param roleId the value for rbac_user_role.role_id
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.creator
     *
     * @return the value of rbac_user_role.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.creator
     *
     * @param creator the value for rbac_user_role.creator
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.modifier
     *
     * @return the value of rbac_user_role.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.modifier
     *
     * @param modifier the value for rbac_user_role.modifier
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.gmt_create
     *
     * @return the value of rbac_user_role.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.gmt_create
     *
     * @param gmtCreate the value for rbac_user_role.gmt_create
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.gmt_modified
     *
     * @return the value of rbac_user_role.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.gmt_modified
     *
     * @param gmtModified the value for rbac_user_role.gmt_modified
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rbac_user_role.is_deleted
     *
     * @return the value of rbac_user_role.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rbac_user_role.is_deleted
     *
     * @param isDeleted the value for rbac_user_role.is_deleted
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}