package com.rany.acl.infra.mapper;

import com.rany.acl.infra.po.ApplicationPO;

public interface ApplicationPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insert(ApplicationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insertSelective(ApplicationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    ApplicationPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKeySelective(ApplicationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKey(ApplicationPO record);
}