package com.rany.acl.infra.mapper;

import com.rany.acl.infra.po.PermissionPO;

public interface PermissionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insert(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insertSelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    PermissionPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKeySelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_permission
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKey(PermissionPO record);
}