package com.rany.acl.infra.mapper;

import com.rany.acl.infra.po.RolePermissionPO;

public interface RolePermissionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    int insert(RolePermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    int insertSelective(RolePermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    RolePermissionPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    int updateByPrimaryKeySelective(RolePermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sat Oct 07 21:45:14 CST 2023
     */
    int updateByPrimaryKey(RolePermissionPO record);
}