package com.rany.acl.infra.mapper;

import com.rany.acl.infra.po.RolePO;

public interface RolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    int insert(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    int insertSelective(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    RolePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    int updateByPrimaryKeySelective(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed Oct 11 22:05:59 CST 2023
     */
    int updateByPrimaryKey(RolePO record);
}