package com.rany.acl.infra.mapper;

import com.rany.acl.infra.po.UserRolePO;

public interface UserRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insert(UserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int insertSelective(UserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    UserRolePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKeySelective(UserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rbac_user_role
     *
     * @mbggenerated Thu Aug 31 22:54:24 CST 2023
     */
    int updateByPrimaryKey(UserRolePO record);
}