package com.rany.ops.infra.mapper;

import com.rany.ops.infra.po.PermissionPO;

public interface PermissionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    int insert(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    int insertSelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    PermissionPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    int updateByPrimaryKeySelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Fri Oct 13 08:37:51 CST 2023
     */
    int updateByPrimaryKey(PermissionPO record);
}