package com.rany.ops.infra.mapper;

import com.rany.ops.infra.po.PermissionPO;

public interface PermissionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    int insert(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    int insertSelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    PermissionPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    int updateByPrimaryKeySelective(PermissionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_permission
     *
     * @mbggenerated Tue Dec 17 10:31:03 CST 2024
     */
    int updateByPrimaryKey(PermissionPO record);
}