package com.rany.ops.infra.mapper;

import com.rany.ops.infra.po.RolePO;

public interface RolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    int insert(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    int insertSelective(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    RolePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    int updateByPrimaryKeySelective(RolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acl_role
     *
     * @mbggenerated Thu Mar 20 22:08:45 CST 2025
     */
    int updateByPrimaryKey(RolePO record);
}