package com.rany.ops.infra.mapper;

import com.rany.ops.infra.po.SafeStrategyPO;

public interface SafeStrategyPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    int insert(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    int insertSelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    SafeStrategyPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    int updateByPrimaryKeySelective(SafeStrategyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safe_strategy
     *
     * @mbggenerated Sun Nov 12 14:20:44 CST 2023
     */
    int updateByPrimaryKey(SafeStrategyPO record);
}