package com.rany.ops.infra.mapper;

import com.rany.ops.infra.po.TenantPO;

public interface TenantPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    int insert(TenantPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    int insertSelective(TenantPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    TenantPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    int updateByPrimaryKeySelective(TenantPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbggenerated Sat Jun 08 15:31:03 CST 2024
     */
    int updateByPrimaryKey(TenantPO record);
}